version: '3.3'
services:
  order_service:
    build: ./pedidoComida
    container_name: order_service
    volumes:
      - ./logs:/app/logs
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.0
    user: root
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/app/logs:ro
    depends_on:
      - order_service
    restart: always

  mongo:
    image: mongo
    container_name: mongo_pedidos
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./pedidoComida/mongo-init:/docker-entrypoint-initdb.d
    restart: always
  
  web:
    build: ./pedidoComida
    security_opt:
      - apparmor=unconfined
    ports:
      - "5000:5000"
    volumes:
      - ./pedidoComida:/app
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/pedidos
  
  faas:
    build:
      context: ./faas
      dockerfile: Dockerfile
    container_name: faas_app
    ports:
      - "8000:8000"
    restart: always

volumes:
  mongo_data:
