version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_pedidos
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d 
    restart: always
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/pedidos
  

volumes:
  mongo_data:
